name: resq_track4
description: A disaster management and AI-powered rescue assistant app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  google_maps_flutter: ^2.5.0
  permission_handler: ^12.0.1
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  speech_to_text: ^7.2.0  # Fixes Kotlin Registrar error

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/Untitled.gif
