name: resq_track4
description: A disaster management and AI-powered rescue assistant app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  google_maps_flutter: ^2.5.0
  permission_handler: ^12.0.1
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.0.3
  firebase_storage: ^12.1.1
  speech_to_text: ^7.2.0  # Fixes Kotlin Registrar error
    # --- قاعدة البيانات المحلية للعمل بدون انترنت (Offline) ---
  sqflite: ^2.3.3+1             # قاعدة بيانات SQLite المحلية
  path_provider: ^2.1.3         # للمساعدة في العثور على مسار حفظ قاعدة البيانات
  flutter_map: ^7.0.1 # بديل مجاني لخرائط جوجل
  latlong2: ^0.9.1    # حزمة مساعدة للتعامل مع إحداثيات الخرائط
  firebase_app_check: ^0.3.0
  change_app_package_name: ^1.5.0
  geolocator: ^12.0.0
  image_picker: ^1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/Untitled.gif
    - lib/assets/logo.jpeg
