// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuOQ2srWMy9kXtwb6e6QqFgoTSidxWU1Q',
    appId: '1:1000011916753:web:c19e5b88bbb7f5c040ecf0',
    messagingSenderId: '1000011916753',
    projectId: 'sos-management-app',
    authDomain: 'sos-management-app.firebaseapp.com',
    storageBucket: 'sos-management-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgehcgRA84d5QDMMR6phH-4AGeEfIVH5M',
    appId: '1:1000011916753:android:eb5c4a1135b6ad8f40ecf0',
    messagingSenderId: '1000011916753',
    projectId: 'sos-management-app',
    storageBucket: 'sos-management-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaX9hwsW0gjvlHTJPLmVpSrezH0kDS8uc',
    appId: '1:1000011916753:ios:09a97a89542fdd0040ecf0',
    messagingSenderId: '1000011916753',
    projectId: 'sos-management-app',
    storageBucket: 'sos-management-app.firebasestorage.app',
    iosBundleId: 'com.example.fatmaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaX9hwsW0gjvlHTJPLmVpSrezH0kDS8uc',
    appId: '1:1000011916753:ios:09a97a89542fdd0040ecf0',
    messagingSenderId: '1000011916753',
    projectId: 'sos-management-app',
    storageBucket: 'sos-management-app.firebasestorage.app',
    iosBundleId: 'com.example.fatmaapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuOQ2srWMy9kXtwb6e6QqFgoTSidxWU1Q',
    appId: '1:1000011916753:web:fad4d59997500e3640ecf0',
    messagingSenderId: '1000011916753',
    projectId: 'sos-management-app',
    authDomain: 'sos-management-app.firebaseapp.com',
    storageBucket: 'sos-management-app.firebasestorage.app',
  );
}
